### ISSUE TITLE
Issue in test suite of metaspades

### ISSUE THREAD

**Issue by tillea** [ablab/spades#872] opened 2021-11-08 09:29 UTC
### Description of bug

    metaspades.py --test

leads to segmentation fault.

I tried to track down the issue via gdb and have added some debug lines to do so.  Please check this [debug code](https://salsa.debian.org/med-team/spades/-/blob/master/debian/patches/debug.patch) I injected into the Debian packaging.  It seems `last_word` becomes zero and than you want to address something at `last_word - 1`.

Hope this helps.

Kind regards
      Andreas.

### spades.log

[spades.log](https://github.com/ablab/spades/files/7495735/spades.log)

### params.txt

[params.txt](https://github.com/ablab/spades/files/7495737/params.txt)

### SPAdes version

3.15.3

### Operating System

Debian (unstable)

### Python Version

Python 3.9.2

### Method of SPAdes installation

Debian package

### No errors reported in spades.log

- [X] Yes

**Comment by asl** [comment] 2021-11-08 09:33
Thanks for letting us know! It seems this is the problem with one of the libraries we're using. So it might take a while to figure out what might be wrong.

**Comment by tillea** [comment] 2021-11-08 10:43
Hi Anton,
thanks a lot for the quick response.
Am Mon, Nov 08, 2021 at 01:33:41AM -0800 schrieb Anton Korobeynikov:
> Thanks for letting us know! It seems this is the problem with one of the libraries we're using. So it might take a while to figure out what might be wrong.
If this might be connected to **third party** libraries please note that due to our policy Debian is not using the code copies shipped with spades but rather the Debian packaged versions.  You can obtain a list of those libraries by inspecting what is actually excluded from your original source tarball in the field [Files-Excluded in debian/copyright](https://salsa.debian.org/med-team/spades/-/blob/master/debian/copyright).  Just to let you know what might potentially influence your debugging process.  Please let me know if you might have changed the code of those third party software or if you possibly stick to a certain version of this.
Kind regards, Andreas.

**Comment by asl** [comment] 2021-11-08 10:48
Well, you can easily compare the sources of the bundled libraries to check for fixes we added. Note that we explicitly do not use external libraries in order to ensure reproducibility, which is often non-existent when the dependent libraries might be broken / changed / have other versions.

Also, may I ask you to change the version of SPAdes in Debian to e.g. 3.15.3-debian to outline that this not the version we shipped / tested?

**Comment by tillea** [comment] 2021-11-08 10:52
> Well, you can easily compare the sources of the bundled libraries to check for fixes we added. Note that we explicitly do not use external libraries in order to ensure reproducibility, which is often non-existent when the dependent libraries might be broken / changed / have other versions.
Is there some documentation about those fixes and did you sent back those fixes to respective upstream.

> Also, may I ask you to change the version of SPAdes in Debian to e.g. 3.15.3-debian to outline that this not the version we shipped / tested?
As usual we rename to 3.15.3+dfsg (which flags a changed upstream source).

Kind regards, Andreas.

**Comment by asl** [comment] 2021-11-08 10:57
> Is there some documentation about those fixes and did you sent back those fixes to respective upstream?

Well, some of them are not maintained anymore as author moved to other projects (pretty common to bioinformatics). We do not explicitly *document* these fixes as we are focusing on something else.

**Comment by tillea** [comment] 2021-11-08 11:12
My point is that we love to take over fixes to Debian packaged libraries that are known to be broken and unmaintained also for users of this library who are not using spades.  So if you create patches for third party code we love to learn about these.

**Comment by asl** [comment] 2021-12-22 07:11
@tillea I studied the code around the issue you reported and something is not wrong. First of all, last_word cannot become 0 as it is guarded in the loop by
```
	while (last_word != first_word) {
```
As `first_word >= 0``, then you cannot enter the loop with `last_word == 0`. What is wrong in your case is that the invariant that `last_word >= first_word` is not satisifed:
```
./assembler/ext/src/gqf/gqf.c (591): Debug: last_word = 643, first_word = 645,  qf->metadata->bits_per_slot = 8
```
This is why `!=` check always happens.

The problem is that I cannot reproduce the issue locally regardless of # of threads used. Can it be that the code is miscompiled somehow by your local gcc? Can you try recompiling with different gcc? Can you try enabling assertions (there is `#if 0` in the beginning of the file that enables assertions always)?

**Comment by emollier** [comment] 2022-04-11 19:27
Hi Anton,

I have been looking at this problem today, and discovered it is related to a change I introduced in _gqf_ to fix a problem of architecture baseline violation more than a year ago which turns out to be the culprit.  I replaced the inline assembly call by a generic ___builtin_popcount_, but did not properly take into account the full width of the _uint64_t_ argument, leading to an overflow of the value and thus an improper result of all _popcnt_ function calls.  Using ___builtin_popcountl_, note the trainling _l_, fixes the overflow and allows me to run the test suite properly.

In case you are interested to provide Spades support to CPU generations older than those which support SSE4, please feel free to make use of the following patch, which didn't raise the present issue on my side:

```patch
--- spades.orig/assembler/ext/src/gqf/gqf.c
+++ spades/assembler/ext/src/gqf/gqf.c
@@ -174,11 +174,7 @@
 
 
 static inline int popcnt(uint64_t val) {
-       asm("popcnt %[val], %[val]"
-                       : [val] "+r" (val)
-                       :
-                       : "cc");
-       return val;
+       return __builtin_popcountl(val);
 }
 
 static inline int popcntv(const uint64_t val, int ignore)
```

There is no problem in your code, it's all my fault.  :(
I think you can close the issue.

With my sincerest apologies,
Étienne.

**Comment by asl** [comment] 2022-04-11 19:44
Thanks for the investigation! Unfortunately, it's not the first time debian-local changes were not quite correct...

**Closed by asl** 2022-04-11 19:44 UTC
Labels: invalid, not a bug

**Comment by asl** [comment] 2022-04-30 11:32
@tillea Let me show you one particular example. Please check the log attached

[spades.log](https://github.com/ablab/spades/files/8596785/spades.log)

As you can see, the memory reporting is plain wrong:
```
  0:11:36.336    27G / 5G    INFO   K-mer Index Building     (kmer_index_builder.hpp    : 298)   Building perfect hash indices
```
it shows e.g. "current consumption of 24G and maximum 5 Gb". This certainly does not make much sense. This was a debian-local patch that caused this.
