### ISSUE TITLE
SPAdes 3.14.0 failure in metagenome assembly

### ISSUE THREAD

**Issue by robertriley6** [ablab/spades#445] opened 2020-02-12 00:17 UTC
Running the command:

spades.py -m 500 -o spades1 --only-assembler -k 33,55,77,99,127 --meta -t 64 -1 CCYCT_reads1.fasta -2 CCYCT_reads2.fasta --pacbio /global/dna/dm_archive/sdm/pacbio/00/17/63/pbio-1763.15716.fastq --pacbio /global/dna/dm_archive/sdm/pacbio/00/17/74/pbio-1774.15803.fastq --pacbio /global/dna/dm_archive/sdm/pacbio/00/17/75/pbio-1775.15811.fastq --pacbio /global/dna/dm_archive/sdm/pacbio/00/17/75/pbio-1775.15812.fastq

Log file:

Command line: /spades/SPAdes-3.14.0-Linux/bin//spades.py	-m	500	-o	/global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/spades1	--only-assembler	-k	33,55,77,99,127	--meta	-t	64	-1	/global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/CCYCT_reads1.fasta	-2	/global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/CCYCT_reads2.fasta	--pacbio	/global/dna/dm_archive/sdm/pacbio/00/17/63/pbio-1763.15716.fastq	--pacbio	/global/dna/dm_archive/sdm/pacbio/00/17/74/pbio-1774.15803.fastq	--pacbio	/global/dna/dm_archive/sdm/pacbio/00/17/75/pbio-1775.15811.fastq	--pacbio	/global/dna/dm_archive/sdm/pacbio/00/17/75/pbio-1775.15812.fastq	

System information:
  SPAdes version: 3.14.0
  Python version: 2.7.5
  OS: Linux-4.12.14-lp150.12.79-default-x86_64-with-centos-7.3.1611-Core

Output dir: /global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/spades1
Mode: ONLY assembling (without read error correction)
Debug mode is turned OFF

Dataset parameters:
  Metagenomic mode
  Reads:
    Library number: 1, library type: pacbio
      left reads: not specified
      right reads: not specified
      interlaced reads: not specified
      single reads: ['/global/dna/dm_archive/sdm/pacbio/00/17/63/pbio-1763.15716.fastq', '/global/dna/dm_archive/sdm/pacbio/00/17/74/pbio-1774.15803.fastq', '/global/dna/dm_archive/sdm/pacbio/00/17/75/pbio-1775.15811.fastq', '/global/dna/dm_archive/sdm/pacbio/00/17/75/pbio-1775.15812.fastq']
      merged reads: not specified
    Library number: 2, library type: paired-end
      orientation: fr
      left reads: ['/global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/CCYCT_reads1.fasta']
      right reads: ['/global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/CCYCT_reads2.fasta']
      interlaced reads: not specified
      single reads: not specified
      merged reads: not specified
Assembly parameters:
  k: [33, 55, 77, 99, 127]
  Repeat resolution is enabled
  Mismatch careful mode is turned OFF
  MismatchCorrector will be SKIPPED
  Coverage cutoff is turned OFF
Other parameters:
  Dir for temp files: /global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/spades1/tmp
  Threads: 64
  Memory limit (in Gb): 500

======= SPAdes pipeline started. Log can be found here: /global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/spades1/spades.log

/global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/CCYCT_reads2.fasta: max reads length: 150
/global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/CCYCT_reads1.fasta: max reads length: 150

Reads length: 150

===== Assembling started. 

===== K33 started. 

== Running: /spades/SPAdes-3.14.0-Linux/bin/spades-core /global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/spades1/K33/configs/config.info /global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/spades1/K33/configs/mda_mode.info /global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/spades1/K33/configs/meta_mode.info

  0:00:00.000     7M / 15M   INFO    General                 (main.cpp                  :  73)   Loaded config from /global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/spades1/K33/configs/config.info
  0:00:00.000     7M / 15M   INFO    General                 (main.cpp                  :  73)   Loaded config from /global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/spades1/K33/configs/mda_mode.info
  0:00:00.000     7M / 15M   INFO    General                 (main.cpp                  :  73)   Loaded config from /global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/spades1/K33/configs/meta_mode.info
  0:00:00.000     7M / 15M   INFO    General                 (memory_limit.cpp          :  49)   Memory limit set to 500 Gb
  0:00:00.000     7M / 15M   INFO    General                 (main.cpp                  :  83)   Starting SPAdes, built from refs/heads/spades_3.14.0, git revision c831f9be30a4364383cd4ebe5b78cdfcaad1acc9
  0:00:00.000     7M / 15M   INFO    General                 (main.cpp                  :  84)   Maximum k-mer length: 128
  0:00:00.000     7M / 15M   INFO    General                 (main.cpp                  :  85)   Assembling dataset (/global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/spades1/dataset.info) with K=33
  0:00:00.001     7M / 15M   INFO    General                 (main.cpp                  :  86)   Maximum # of threads to use (adjusted due to OMP capabilities): 36
  0:00:00.001     7M / 15M   INFO    General                 (launch.hpp                :  79)   SPAdes started
  0:00:00.001     7M / 15M   ERROR   General                 (launch.hpp                :  82)   Sorry, current version of metaSPAdes can work either with single library (paired-end only) or in paired-end + (TSLR or PacBio or Nanopore) mode.

== Error ==  system call for: "['/spades/SPAdes-3.14.0-Linux/bin/spades-core', '/global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/spades1/K33/configs/config.info', '/global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/spades1/K33/configs/mda_mode.info', '/global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/spades1/K33/configs/meta_mode.info']" finished abnormally, OS return value: 239

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/spades1/spades.log

Thank you for using SPAdes!

The same command finished successfully using 3.13.0.  Thanks!

**Comment by asl** [comment] 2020-02-12 11:17
Hello

Thank you for your interest in SPAdes.

Looks like a very nasty regression introduced in SPAdes 3.14 and will be fixed in 3.14.1.

The workaround as follows: create a YAML dataset description file (or edit /global/cscratch1/sd/rwriley/metagenome/GAA-6918_Hybrid_assembly_PacBio-Illumina_for_metaG/spades1/input_dataset.yaml). The paired-end library should be the first there and pacbio – the second one.

**Comment by asl** [comment] 2020-12-13 18:03
Will be fixed in 3.15

**Closed by asl** 2020-12-13 18:03 UTC
