### ISSUE TITLE
hqmp assemblies never finish in 3.12

### ISSUE THREAD

**Issue by osvatic** [ablab/spades#151] opened 2018-07-25 13:05 UTC
I have been trying to run 2 hqmp assemblies in 3.12 and both stall (not exit or error) after the final kmer.

Is there a way around this? or is it a major bug?

Thank you!

**Comment by asl** [comment] 2018-07-25 16:24
@andrewprzh will probably the best person to help with it

**Comment by andrewprzh** [comment] 2018-07-28 02:10
Sorry for a delay -- replied by email.

**Comment by waterfleas** [comment] 2018-11-05 12:40
I have the same problem in both 3.12 and 3.13 assemblies, but no with hqmp.  No error and no exit.

**Comment by andrewprzh** [comment] 2022-07-16 10:20
Please re-open if the problem is not resolved in the latest release.

**Closed by andrewprzh** 2022-07-16 10:20 UTC
