### ISSUE TITLE
rnaspades run error

### ISSUE THREAD

**Issue by Genan-blur** [ablab/spades#647] opened 2021-01-18 12:04 UTC
Hi:

There is an error during my rnaspades run. It automatically chooses the K-mer size of 49 and 73. The assembly of k-mer size 49 is finished, and I was stacked in the 73-kmer size assembly.

Here is the error message:
== Error ==  system call for: "['/home/ubuntu/SPAdes-3.15.0-Linux/bin/spades-core', '/data/acetate_trinity/Spades/K73/configs/config.info', '/data/acetate_trinity/Spades/K73/configs/mda_mode.info', '/data/acetate_trinity/Spades/K73/configs/rna_mode.info']" finished abnormally, OS return value: -6

btw I used 16 CPUs and 32 RAM 
So, does it mean that I am running out of the memory?

Thanks a lot
[spades.log](https://github.com/ablab/spades/files/5830049/spades.log)

**Comment by asl** [comment] 2021-01-18 12:12
Hello

This looks like a bug in SPAdes. Will it be possible for you to share your data with us so we could reproduce and fix it?

**Comment by Genan-blur** [comment] 2021-01-18 14:59
Of course, did you mean my fastq reads? But I am new to the Github. I found I can't upload a file that excess 100M to the repository. How can I share my data with you?

**Comment by asl** [comment] 2021-01-18 15:06
Whatever way is convenient for you. E.g. weshare, google driver, etc.

**Comment by Genan-blur** [comment] 2021-01-18 20:00
Hi, 

I have uploaded the files to https://share.weiyun.com/Svs7GvJI, and the password is jgcy3h

I don't know whether this cloud driver is convenient for you to download, but I can try some other methods if it doesn't work. 

Thanks

**Comment by asl** [comment] 2021-01-18 20:48
Thanks! Tagging @olga24912

**Comment by davidsilvapires** [comment] 2021-01-27 18:49
Hi.

We had the same error:

== Error ==  system call for: "['/usr/local/src/spades/3.15.0-src/SPAdes-3.15.0/bin/spades-core', '/mnt/project1/.../teste_spades/K29/configs/config.info', '/mnt/project1/.../teste_spades/K29/configs/mda_mode.info', '/mnt/project1/.../teste_spades/K29/configs/rna_mode.info']" finished abnormally, OS return value: -6

We got the same message while trying to run with version 3.15.0 (compiled locally), 3.15.0 (binary distribution), and 3.14.1 (compiled locally).

The OS is Linux Ubuntu 18.04 LTS.

Do you think it is worth to try older versions of Spades in order to determine what is the most recent one that do not contains the bug?

Tell us if we can help with something.

Thanks in advance for any help.

--
David da Silva Pires

**Comment by asl** [comment] 2021-01-27 19:14
@davidsilvapires you bug is likely different. Please open a new issue attaching the files mentioned in the error message.

Thanks!

**Comment by asl** [comment] 2021-01-27 19:15
@Genan-blur Thanks, we fixed your problem. It only occurs when multiple libraries are used. The fix will be included into SPAdes 3.15.1

**Closed by asl** 2021-01-27 19:15 UTC
