### ISSUE TITLE
rnaSPAdes error -6 Assertion failed

### ISSUE THREAD

**Issue by yyan823** [ablab/spades#140] opened 2018-07-09 17:20 UTC
Dear developers,

We got this error message while using rnaSPAdes (SPAdes 3.12.0) for denovo transcriptome assembly. 3 out of 48 datasets faced this problem. We restarted but didn't work. Could you please help to see where is the problem and how could we solve this?

Here is the error message:
......
  0:05:29.076     1G / 8G    INFO    General                 (path_extender.hpp         : 883)   Processed 8192 paths from 98519 (8%)
  0:05:29.469     1G / 8G    INFO    General                 (path_extender.hpp         : 885)   Processed 9852 paths from 98519 (10%)
  0:05:32.824     1G / 8G    INFO    General                 (path_extender.hpp         : 883)   Processed 16384 paths from 98519 (16%)
  0:05:33.647     1G / 8G    INFO    General                 (path_extender.hpp         : 885)   Processed 19704 paths from 98519 (20%)

=== Stack Trace ===
0   spades-core                         0x000000010902129f _ZN5utils16print_stacktraceEv + 63
1   ???                                 0x00007ffe00000000 0x0 + 140728898420736
Assertion failed: (path.Length() > 0), function EstimatePathCoverage, file /Users/asl/Temp/SPAdes-3.12.0/src/common/modules/path_extend/weight_counter.hpp, line 295.

== Error ==  system call for: "['/Users/katzlab_agnes/Desktop/Assembly/SPAdes-3.12.0-Darwin/bin/spades-core', '/Users/katzlab_agnes/Desktop/Assembly/LKH333_Sr_rh_Pp01/K55/configs/config.info', '/Users/katzlab_agnes/Desktop/Assembly/LKH333_Sr_rh_Pp01/K55/configs/mda_mode.info', '/Users/katzlab_agnes/Desktop/Assembly/LKH333_Sr_rh_Pp01/K55/configs/rna_mode.info']" finished abnormally, err code: -6

Thank you!
Ying

**Comment by yyan823** [comment] 2018-07-09 19:52
Dear Andreu,

Thank you for your reply. We are really sorry but these datasets are not published yet. Would it be helpful if we share the spades.log file with you? We've also run the three with 3.10.1 (the last version we used before 3.12.0), two of them worked, and one left with the similar error code.

Thanks,
Ying
[spades.log](https://github.com/ablab/spades/files/2177761/spades.log)

**Comment by andrewprzh** [comment] 2018-07-28 02:06
Dear Ying,

The errors seem to be different and it's quite hard to tell what is the exact reason just by the log file. 

The second case may look like an our of memory error, is it possible to rerun the same jobs with more RAM?

Best
Andrey

**Comment by andrewprzh** [comment] 2018-09-05 23:51
Dear Ying

We have a fix for the first error you've sent. This fix will be included in the next release. If you need the fixed version ASAP, please write me directly to andrewprzh@gmail.com and I will send you the fix.

Best
Andrey

**Comment by reBiocoder** [comment] 2018-10-29 09:09
it could out  of  memory

**Comment by andrewprzh** [comment] 2022-07-16 10:20
Please re-open if the problem is not resolved in the latest release.

**Closed by andrewprzh** 2022-07-16 10:20 UTC
