### ISSUE TITLE
poly-N run in contigs.fasta

### ISSUE THREAD

**Issue by PeterSlickers** [ablab/spades#130] opened 2018-06-20 22:00 UTC
So far I have never seen any N in contigs assembled with spades. But after upgrading to version 3.12.0, I suddenly recognized a poly-N run in a contig. In my understanding, poly-N runs may be introduced into scaffolds, but they should never appear in contigs. 

Initially, I had recognized the poly-N run in an assembly of one of our own sequences, but I have found a publicaly available dataset now, where it also happens.

`wget -N http://ftp.sra.ebi.ac.uk/vol1/fastq/ERR243/005/ERR2437215/ERR2437215_1.fastq.gz`

`wget -N http://ftp.sra.ebi.ac.uk/vol1/fastq/ERR243/005/ERR2437215/ERR2437215_2.fastq.gz`

`spades.py -k 21,33,55,77,99,127 --careful -o spades_out --pe1-1 ERR2437215_1.fastq.gz --pe1-2 ERR2437215_2.fastq.gz`

`grep NNN spades_out/contigs.fasta`

`GTGGCTCTTATGCAGTTGGAGCGAAGATCCAACTGTACNNNNNNNNNNNNNNNNNNNNNN`
`NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN`
`NNNNNNNNNNNNNNNNAAACCGCGACATTATAGAGCCAATCACTAGCCTATCTCAGAATC`

Please note, that this poly-N run is introduced into a tandem repeat. The repeat unit at the site of the poly-N run is a 69-mer:

`GGTTTACAGTTGGATCTTCGCTCCAACTGCATAAGAGCCACTAATTATTATAAATAATAAGTACACTAT`

The  read-set ERR2437215 belongs to a Staphylococcus aureus clonal complex 398. Other sequences of this clonal complex have 3 to 6 identical copies of the repeat unit at this site.

**Comment by andrewprzh** [comment] 2018-07-03 17:24
Dear Peter!

Thanks a lot for the report and for the data. We have reproduced and localized the bug. We will fix in the nearest release (most likely 3.12.1). 

By the way, your data has maximal read length of 151 and mean 140.236 (after correction). I would not recommend raising maximal K that high, automatic k (which goes up to 77) should be enough. Current run with maximal K = 127 even gives several warnings in the end and the results may be sub-optimal.

Best
Andrey

**Comment by andrewprzh** [comment] 2018-07-04 18:42
The issue is resolved and will be fixed in 3.12.1.

**Closed by andrewprzh** 2018-07-04 18:42 UTC
