### ISSUE TITLE
finished abnormally, err code: -6

### ISSUE THREAD

**Issue by qslin** [ablab/spades#56] opened 2017-12-23 22:33 UTC
What does the error mean and how to solve it? Thank you!
[spades.log](https://github.com/ablab/spades/files/1584478/spades.log)
[params.txt](https://github.com/ablab/spades/files/1584479/params.txt)

**Comment by asl** [comment] 2017-12-23 22:44
Hello

Thank you for your interest in SPAdes. This is known issue that will be fixed in SPAdes 3.12

**Comment by kingcohn1** [comment] 2017-12-26 21:31
Great, when will this version be clonable?

**Comment by asl** [comment] 2017-12-26 21:35
Hopefully sometime in January.

**Comment by kingcohn1** [comment] 2017-12-26 21:46
thank you!

**Comment by roshanpais** [comment] 2018-03-21 06:42
Hello, I have a similar problem. This is my first time using an assembler.  Please help to troubleshoot, thank you.
[params.txt](https://github.com/ablab/spades/files/1832245/params.txt)
[spades.log](https://github.com/ablab/spades/files/1832246/spades.log)

**Comment by asl** [comment] 2018-03-21 07:37
@roshanpais The issue is completely different. The log reads:
```
<jemalloc>: Error in malloc(): out of memory. Requested: 3484059104, active: 16672358400
```
So, you're out of RAM.

**Comment by tseemann** [comment] 2018-04-02 20:59
@asl we just got this today when running in a Singularity container:
```
<jemalloc>: Error in malloc(): out of memory. Requested: 144176, active: 8422162
432
```
We ran Spades with `--ram 8` on a simpel 76x illumina bacteral genome.

I assume the `8422162432` is related to the `--ram 8` ?

8 G = 8*1024^3 = 8589934592 bytes?
8,422,162,432 - 8,422,162,432 = 167772160 = 16*1024^2 = 16 Mbytes

Is it really failing because it can't get 144176 bytes of ram?

**Comment by asl** [comment] 2018-04-02 21:24
Hi @tseemann 

Indeed, at the point of failure SPAdes has 7.84375 Gb of RAM allocated. And the OS failed to fulfill SPAdes' request to allocate 144 Kb more, indeed. We had no other way than to forward this error to user.

**Comment by asl** [comment] 2018-04-02 21:32
Most probably the native system allows some overcommit. Or something like this...

**Comment by tseemann** [comment] 2018-04-02 21:36
What is the "missing" 16 MB from the `jmalloc` 8 GB ?

**Comment by asl** [comment] 2018-04-02 21:52
There is nothing missed. jemalloc allocated 7.84 Gb of VM from OS for memory allocation. And as unable to increase that amount.

**Comment by ctxchris** [comment] 2018-04-09 11:33
Hi Anton,

will  SPAdes 3.12 be released soon?

Thx,
Christian

**Comment by asl** [comment] 2018-04-09 11:34
Hopefully – yes.

**Comment by tseemann** [comment] 2018-04-22 04:44
@ctxchris is your question related to this issue - just wondering if 3.12 will fix it

**Comment by ctxchris** [comment] 2018-04-23 07:10
@tseemann yes, we get the same error message a described above. Hopefully the update will fix it.

**Comment by Yanfei-Geng** [comment] 2018-04-23 07:17
will SPAdes 3.12 be released soon for killing  "finished abnormally, err code: -6"? thx

**Comment by jhernandez1409** [comment] 2018-05-09 18:18
Hi,

I also have the same error (-6 ) when trying to run plasmidspades. Could you help me please? I have attached the logs.
[warnings.log](https://github.com/ablab/spades/files/1988985/warnings.log)
[spades.log](https://github.com/ablab/spades/files/1988990/spades.log)

Thanks in advance!

**Comment by asl** [comment] 2018-05-09 19:43
Let us read the log together:

```
Message 'Invalid kmer coverage histogram, make sure that the coverage is indeed uniform'.
```
You're having just 1245 reads – I doubt they are from some genome / part of the genome.

**Comment by jhernandez1409** [comment] 2018-05-12 20:03
Hi Anton,

Thank you for your help. I am sorry, I am new on this so I dont know much.
I dont understand what it means with the coverage being uniform?

This is one of the fastq files we received after sending some bacterial DNA
out for sequencing. The genome size should be around 4-5.5 MB, and I just
want to extract the potential plasmids reads and assemble those.

Any advise will be very much appreciate it.

Thank you so much :)

JoJo

**Comment by asl** [comment] 2018-06-27 17:35
The original issue was fixed in SPAdes 3.12

**Closed by asl** 2018-06-27 17:35 UTC

**Comment by asl** [comment] 2018-12-11 21:30
The log reads:

```
 0:35:04.387   496M / 3G    ERROR  K-mer Counting           (kmer_data.cpp             : 353)   The reads contain too many k-mers to fit into available memory. You need approx. 35.7545GB of free RAM to assemble your dataset
```

So, you need more RAM to assemble this dataset.

As for the second log, we're seeing:
```
spades-hammer: /spades/src/common/utils/kmer_mph/kmer_index_builder.hpp:205: size_t utils::KMerDiskCounter<Seq, traits>::MergeKMers(const string&, const string&) [with Seq = Seq<21ul>; traits = utils::kmer_index_traits<Seq<21ul> >; size_t = long unsigned int; std::string = std::basic_string<char>]: Assertion `std::is_sorted(beg, end, adt::array_less<typename Seq::DataType>())' failed.
```
So, it's the same I/O problem as before.

**Comment by StrakaJ1** [comment] 2019-02-14 14:50
Hello,
I get similar problem as the original one. Can you help with resolving it?

[spades.log](https://github.com/ablab/spades/files/2865492/spades.log)
[params.txt](https://github.com/ablab/spades/files/2865493/params.txt)

**Comment by asl** [comment] 2019-02-14 22:35
@StrakaJ1 your problem is completely different. I would suggest you to open new issues and not to hijack the closed ones. I believe you're having non-ACGTN symbols in your contigs.

**Comment by vdnadung** [comment] 2019-02-15 07:08
Hello,

I have similar issue. Can you please help?

Thank you in advance.
[spades.log](https://github.com/ablab/spades/files/2868126/spades.log)
[params.txt](https://github.com/ablab/spades/files/2868129/params.txt)

**Comment by asl** [comment] 2019-02-15 08:35
@vdnadung Please do not hijack the closed issue and open a new one.
